debug: true

logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      springframework:
        web:
          client.RestTemplate: DEBUG
        security: DEBUG
        cloud: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:demo}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth
          uri: ${AUTHORIZATION_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
        - id: users
          uri: ${RESOURCE_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
